FROM rabbitmq:3-management
COPY ./rabbitmq/rabbitmq.config /etc/rabbitmq
ADD --chown=rabbitmq ./rabbitmq/definitions.json /etc/rabbitmq/
RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.config /etc/rabbitmq/definitions.json
CMD ["rabbitmq-server"]