# version: '3.5'

services:
  db:
    container_name: postgres-15.5
    image: postgres:15.5-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - fluxus5db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  fluxus5db: